### ISSUE TITLE
change db migration - issue when deploy to Heroku

### ISSUE THREAD

**Issue by tony-luisi** [SamSimmons/who-hi#15]
Hey @vickenliu, @oliver-jk-redding 

The migration file creates a cohort table with an image column of type integer. This needs to be updated to take urls.

Cannot seed to database on heroku.

Please change.

Thanks

**Comment by oliver-jk-redding** [comment]
@tony-luisi Weird. On my local copy it is showing as type string which is what I set it when I made it. Someone must have changed it. @vickenliu ?

**Comment by vickenliu** [comment]
solved :)
